-- CreateTable
CREATE TABLE "RSVP" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "organization" TEXT,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "attendanceStatus" TEXT NOT NULL,
    "attendeeCount" INTEGER NOT NULL,
    "dietaryPreference" TEXT NOT NULL,
    "dietaryOther" TEXT,
    "accessibilityNeeds" TEXT,
    "referralSource" TEXT NOT NULL,
    "referralOther" TEXT,
    "wantsResources" BOOLEAN NOT NULL DEFAULT false,
    "wantsAudit" BOOLEAN NOT NULL DEFAULT false,
    "learningGoal" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visitorId" TEXT,
    "sessionId" TEXT,
    "referrer" TEXT,
    "eid" TEXT,
    "utmSource" TEXT,
    "utmMedium" TEXT,
    "utmCampaign" TEXT,
    "utmTerm" TEXT,
    "utmContent" TEXT,
    "userAgent" TEXT,
    "language" TEXT,
    "tz" TEXT,
    "country" TEXT,
    "region" TEXT,
    "city" TEXT,
    "ipHash" TEXT,
    "screenW" INTEGER,
    "screenH" INTEGER,
    "dpr" DOUBLE PRECISION,
    "platform" TEXT,
    "device" TEXT,
    "browser" TEXT,
    "meta" TEXT,

    CONSTRAINT "RSVP_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Visit" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visitorId" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "query" TEXT,
    "referrer" TEXT,
    "eid" TEXT,
    "utmSource" TEXT,
    "utmMedium" TEXT,
    "utmCampaign" TEXT,
    "utmTerm" TEXT,
    "utmContent" TEXT,
    "gclid" TEXT,
    "fbclid" TEXT,
    "msclkid" TEXT,
    "userAgent" TEXT,
    "language" TEXT,
    "tz" TEXT,
    "screenW" INTEGER,
    "screenH" INTEGER,
    "dpr" DOUBLE PRECISION,
    "platform" TEXT,
    "device" TEXT,
    "browser" TEXT,
    "country" TEXT,
    "region" TEXT,
    "city" TEXT,
    "ipHash" TEXT,

    CONSTRAINT "Visit_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "RSVP_email_key" ON "RSVP"("email");
